---
- hosts: master
  gather_facts: false
  become_user: root
  become: yes
  tags:
    - common
  roles:
    - common
    - master

- hosts: worker
  gather_facts: fasle
  become_user: root
  become: yes
  tags:
    - worker
  roles:
    - common
    - worker