---
- hosts: master
  gather_facts: true
  become_user: root
  become: yes
  tags:
    - master
  roles:
    - docker
    - kubernetes
    - master

- hosts: worker
  gather_facts: true
  become_user: root
  become: yes
  tags:
    - worker
  roles:
    - docker
    - kubernetes
    - worker
