---
- name: Copy local hosts file to etc folder
  become: yes
  copy: src=hosts dest=/etc/

- name: Add the user 'ubuntu' with a bash shell, appending the group 'vagrant' to the user's groups
  user:
    name: ubuntu
    shell: /bin/bash
    groups: vagrant
    append: yes

- name: Copy files in .ssh folder
  become: yes
  copy:
    src: /home/vagrant/.ssh/
    dest: /home/ubuntu/
    remote_src: yes

- name: Add permissions to folder ubuntu
  file:
    path: /home/ubuntu
    owner: ubuntu
    group: ubuntu

- name: Update cache
  apt:
    name: aptitude
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: ['python-minimal', 'python-apt', 'python-setuptools', 'python-pip']
