---
- name: Add helm chart repo
  become: no
  command: helm repo add istio.io https://storage.googleapis.com/istio-release/releases/1.3.0/charts/
  changed_when: false

- name: Copy Istio files
  copy:
    src: files/
    dest: /tmp/istio
    owner: vagrant
    group: vagrant
  changed_when: false

- name: Create namespace istio-system
  become: no
  command: kubectl apply -f /tmp/istio/namespace.yaml
  changed_when: false

- name: Install istio CRDS 
  become: no
  shell: > 
    helm template /tmp/istio/istio-init --name istio-init --namespace istio-system | kubectl apply -f -
  changed_when: false

- name: Verify, if CRDS is running
  become: no
  shell: kubectl get crds | grep 'istio.io' | wc -l
  register: crds_out
  until: crds_out.stdout is search("23")
  retries: 30
  delay: 20

- name: Show crds result
  debug:
    var: crds_out

- name: Apply Istio core components 
  become: no
  shell: > 
    helm template /tmp/istio/istio --name istio --namespace istio-system --values /tmp/istio/istio/values-istio-demo.yaml | kubectl apply -f -
  changed_when: false