- name: Initialize kubeadm on master
  become: yes
  shell: kubeadm reset -f && kubeadm init --apiserver-advertise-address=10.0.0.10 --pod-network-cidr=10.244.0.0/16
  register: kubeadm_out
  args:
    creates: /etc/kubeadm-join.sh

- name: Printing kubeadm init result
  debug:
    var: kubeadm_out
  
- name: Adding join to /etc/kubeadm-join.sh
  lineinfile:
    path: /etc/kubeadm-join.sh
    line: "{{kubeadm_out.stdout_lines[-2]}}"
    create: yes
    state: present
  register: changed
  when: kubeadm_out.stdout.find("kubeadm join") != -1

- name: Adding the rest to /etc/kubeadm-join.sh
  lineinfile:
    path: /etc/kubeadm-join.sh
    line: "{{kubeadm_out.stdout_lines[-1]}}"
    insertafter: '\\'
    state: present
  when: kubeadm_out.changed

- name: ansible create directory with mode setting example
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant

- name: Copy file with owner and permissions
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Install calico or flannel pod network
  become: no
  #command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  command: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml

- name: Generate join command
  become: yes
  command: kubeadm token create --print-join-command
  register: join_command

- name: Printing result from token task
  debug:
    var: join_command

- name: Copy join command to local file
  become: no
  delegate_to: localhost
  copy: 
    content: "{{ join_command.stdout_lines[0] }}" 
    dest: "./join-command"

- name: Verify, if master node is ready
  become: no
  shell: kubectl get nodes
  register: master_node_out
  until: master_node_out.stdout is search("Ready")
  retries: 2
  delay: 1

- name: Printing nodes result
  debug:
    var: master_node_out



