---
- name: Create rook directory
  become: yes
  file:
    path: /var/lib/rook
    state: directory
    mode: '0777'

- name: Create registry directory
  become: yes
  file:
    path: /var/lib/registry
    state: directory
    mode: '0777'

- name: Rook Common | Copy common file
  become: no
  local_action: copy content="{{ role_path }}"/files/common.yml dest="./common.yml"

- name: Rook Operator | Copy operator file 
  become: no
  local_action: copy content="{{ role_path }}"/files/operator.yml dest="./operator.yml"

- name: Rook Operator | Copy the operator file to server location
  become: no
  copy: src=operator.yml dest=/tmp/operator.yml mode=0777

- name: Rook Common | Copy the common file to server location
  become: no
  copy: src=common.yml dest=/tmp/common.yml mode=0777

- name: Rook Cluster | Copy cluster file 
  become: no
  local_action: copy content="{{ role_path }}"/files/cluster.yml dest="./cluster.yml"

- name: Rook Cluster | Copy the cluster file to server location
  become: no
  copy: src=cluster.yml dest=/tmp/cluster.yml mode=0777

- name: Rook Toolbox | Copy toolbox file 
  become: no
  local_action: copy content="{{ role_path }}"/files/toolbox.yml dest="./toolbox.yml"

- name: Rook Toolbox | Copy the toolbox file to server location
  become: no
  copy: src=toolbox.yml dest=/tmp/toolbox.yml mode=0777

- name: Rook File System | Copy file system file 
  become: no
  local_action: copy content="{{ role_path }}"/files/filesystem.yml dest="./filesystem.yml"

- name: Rook File System | Copy the file system file to server location
  become: no
  copy: src=filesystem.yml dest=/tmp/filesystem.yml mode=0777

- name: Rook Docker Registry | Copy registry file 
  become: no
  local_action: copy content="{{ role_path }}"/files/registry.yml dest="./registry.yml"

- name: Rook Docker Registry | Copy the registry file to server location
  become: no
  copy: src=registry.yml dest=/tmp/registry.yml mode=0777

- name: Rook Common | Install rook common
  become: no
  command: kubectl apply -f /tmp/common.yml 

- name: Rook Operator | Install rook operator
  become: no
  command: kubectl apply -f /tmp/operator.yml

- name: Verify, if rook disover is running
  become: no
  shell: kubectl get pods -l app=rook-discover -n rook-ceph
  register: rook_discover_out
  until: rook_discover_out.stdout.find("Running") != -1
  retries: 30
  delay: 20

- name: Show rook discover result
  debug:
    var: rook_discover_out

- name: Verify, if rook-ceph-operator is running
  become: no
  shell: kubectl get pods -l app=rook-ceph-operator -n rook-ceph
  register: rook_operator_out
  until: rook_operator_out.stdout.find("Running") != -1
  retries: 30
  delay: 20

- name: Show rook operator result
  debug:
    var: rook_operator_out

- name: Rook Cluster | Install rook cluster
  become: no
  command: kubectl apply -f /tmp/cluster.yml 

- name: Rook Toolbox | Install rook toolbox
  become: no
  command: kubectl apply -f /tmp/toolbox.yml

- name: Rook File System | Install rook file system
  become: no
  command: kubectl apply -f /tmp/filesystem.yml

- name: Rook Docker Registry | Install docker registry
  become: no
  command: kubectl apply -f /tmp/registry.yml

