---
- name: Copy Rook files
  copy:
    src: files/
    dest: /tmp/rook
  changed_when: false

- name: Rook Common | Install rook common
  become: no
  command: kubectl apply -f /tmp/rook/common.yml
  changed_when: false

- name: Rook Operator | Install rook operator
  become: no
  command: kubectl apply -f /tmp/rook/operator.yml
  changed_when: false

- name: Verify, if rook disover is running
  become: no
  shell: kubectl get pods -l app=rook-discover -n rook-ceph
  register: rook_discover_out
  until: rook_discover_out.stdout.find("Running") != -1
  retries: 30
  delay: 100

- name: Show rook discover result
  debug:
    var: rook_discover_out

- name: Verify, if rook-ceph-operator is running
  become: no
  shell: kubectl get pods -l app=rook-ceph-operator -n rook-ceph
  register: rook_operator_out
  until: rook_operator_out.stdout.find("Running") != -1
  retries: 30
  delay: 100

- name: Show rook operator result
  debug:
    var: rook_operator_out

- name: Rook Cluster | Install rook cluster
  become: no
  command: kubectl apply -f /tmp/rook/cluster.yml
  changed_when: false

- name: Rook Toolbox | Install rook toolbox
  become: no
  command: kubectl apply -f /tmp/rook/toolbox.yml
  changed_when: false

- name: Rook Object Storage | Install rook object storage
  become: no
  command: kubectl apply -f /tmp/rook/object.yml
  changed_when: false

- name: Verify, if rook object storage is running
  become: no
  shell: kubectl -n rook-ceph get pod -l app=rook-ceph-rgw
  register: rook_object_storage_out
  until: rook_object_storage_out.stdout.find("Running") != -1
  retries: 30
  delay: 100

- name: Rook Object User | Install rook object user
  become: no
  command: kubectl apply -f /tmp/rook/object-user.yml
  changed_when: false

- name: Verify, if rook object user is running
  become: no
  shell: kubectl -n rook-ceph get secret rook-ceph-object-user-my-store-my-user
  register: rook_ceph_object_user_out
  until: rook_ceph_object_user_out.stdout.find("rook-ceph-object-user-my-store-my-user") != -1
  retries: 30
  delay: 100

- name: Show rook object storage
  debug:
    var: rook_ceph_object_user_out